name: vscode-binder
channels:
  - conda-forge
dependencies:
  - black
  - isort
  - jupyterlab_code_formatter
  - autopep8
  - numpy
  - python-build
  - jupyter-server-proxy=3.2.1
  - code-server=4.1.0
  - jupytext
  - matplotlib
  - pandas
  - papermill
  - scikit-learn
